// Generated by tools/i18n/export.py. Do not edit by hand.

/// Exercise names and instructions per language, keyed by exercise id.
enum ExerciseTranslations {
    static let json = #"""
{"es":{},"pt":{}}
"""#
}
