// Generated by tools/i18n/export.py. Do not edit by hand.

/// Translations of UI and engine text, keyed by the English string.
enum LocalizationData {
    static let json = #"""
{"es":{},"pt":{}}
"""#
}
