"""Write Momentum/Models/ExerciseTranslations.swift from tools/i18n/exercises.py.

Validates that every exercise id in data/exercises.json has a Spanish and a
Portuguese entry with the same number of steps as the English source.
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from exercises import ES, PT  # noqa: E402

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
LIBRARY = os.path.join(ROOT, 'data', 'exercises.json')
OUT = os.path.join(ROOT, 'Momentum', 'Models', 'ExerciseTranslations.swift')


def english_steps():
    """{id: [step, ...]} from data/exercises.json."""
    with open(LIBRARY, encoding='utf-8') as handle:
        return {e['id']: e['steps'] for e in json.load(handle)}


def validate(english):
    errors = []
    for lang, table in (('es', ES), ('pt', PT)):
        for ex_id, steps in english.items():
            entry = table.get(ex_id)
            if entry is None:
                errors.append(f'{lang}: missing {ex_id}')
                continue
            if not isinstance(entry.get('name'), str) or not entry['name'].strip():
                errors.append(f'{lang}: {ex_id} has no name')
            got = entry.get('steps')
            if not isinstance(got, list) or len(got) != len(steps):
                errors.append(f'{lang}: {ex_id} has {len(got or [])} steps, English has {len(steps)}')
            elif not all(isinstance(s, str) and s.strip() for s in got):
                errors.append(f'{lang}: {ex_id} has an empty step')
        for ex_id in table:
            if ex_id not in english:
                errors.append(f'{lang}: unknown id {ex_id}')
    return errors


def main():
    english = english_steps()
    if not english or any(not s for s in english.values()):
        sys.exit('no exercises found in data/exercises.json')
    errors = validate(english)
    if errors:
        sys.exit('\n'.join(errors))

    payload = json.dumps({'es': ES, 'pt': PT}, ensure_ascii=False, sort_keys=True, separators=(',', ':'))
    if '"""#' in payload:
        sys.exit('JSON contains a raw-string terminator')

    swift = (
        '// Generated by tools/i18n/export_exercises.py. Do not edit by hand.\n'
        '\n'
        '/// Exercise names and instructions per language, keyed by exercise id.\n'
        'enum ExerciseTranslations {\n'
        '    static let json = #"""\n'
        f'{payload}\n'
        '"""#\n'
        '}\n'
    )
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(swift)
    print(f'wrote {os.path.relpath(OUT, ROOT)}: {len(english)} exercises x 2 languages')


if __name__ == '__main__':
    main()
