#!/usr/bin/env python3
"""Merge tools/i18n/strings_*.py (ES/PT dicts), validate against the keys found in the
Swift sources, and generate Momentum/Models/LocalizationData.swift.

Usage: python3 tools/i18n/export.py [--strict]
  --strict  exit with status 1 if any key is missing in any language
            (or a placeholder set mismatches).
"""
import glob, importlib.util, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import extract  # noqa: E402

OUT = os.path.normpath(os.path.join(HERE, '..', '..', 'Momentum', 'Models', 'LocalizationData.swift'))
LANGS = ('ES', 'PT')
PLACEHOLDER = re.compile(r'\{(\d+)\}')


def load_modules():
    mods = []
    for path in sorted(glob.glob(os.path.join(HERE, 'strings_*.py'))):
        name = os.path.splitext(os.path.basename(path))[0]
        spec = importlib.util.spec_from_file_location(name, path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        mods.append((name, mod))
    return mods


def merge(mods):
    merged = {lang: {} for lang in LANGS}
    for name, mod in mods:
        for lang in LANGS:
            for k, v in getattr(mod, lang, {}).items():
                if k in merged[lang] and merged[lang][k] != v:
                    print(f'warning: {lang} key redefined in {name}: {k!r}', file=sys.stderr)
                merged[lang][k] = v
    return merged


def main():
    strict = '--strict' in sys.argv[1:]
    keys = set(extract.keys())
    merged = merge(load_modules())
    problems = 0
    out = {}

    for lang in LANGS:
        tr = merged[lang]
        missing = sorted(keys - set(tr))
        stale = sorted(set(tr) - keys)
        bad = sorted(k for k in keys & set(tr) if set(PLACEHOLDER.findall(k)) != set(PLACEHOLDER.findall(tr[k])))
        if missing:
            problems += len(missing)
            print(f'[{lang}] {len(missing)} missing key(s):', file=sys.stderr)
            for k in missing:
                print(f'    {k!r}', file=sys.stderr)
        for k in stale:
            print(f'warning: [{lang}] stale translation (not in code): {k!r}', file=sys.stderr)
        for k in bad:
            problems += 1
            print(f'error: [{lang}] placeholder mismatch: {k!r} -> {tr[k]!r}', file=sys.stderr)
        out[lang.lower()] = {k: tr[k] for k in keys if k in tr and k not in bad}
        print(f'{lang}: {len(out[lang.lower()])}/{len(keys)} keys translated', file=sys.stderr)

    payload = json.dumps(out, ensure_ascii=False, sort_keys=True, separators=(',', ':'))
    if '"""#' in payload:
        sys.exit('error: payload contains the raw-string terminator')
    swift = ('// Generated by tools/i18n/export.py. Do not edit by hand.\n\n'
             '/// Translations of UI and engine text, keyed by the English string.\n'
             'enum LocalizationData {\n'
             '    static let json = #"""\n'
             f'{payload}\n'
             '"""#\n'
             '}\n')
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(swift)
    print(f'wrote {os.path.relpath(OUT)}', file=sys.stderr)
    if strict and problems:
        sys.exit(1)


if __name__ == '__main__':
    main()
