"""Merge all motion modules and write Momentum/Design/MotionData.swift (JSON payload)."""
import json, re, sys, os
import motions_a, motions_b, motions_c
from preview import bbox, cycle_frames

allm = {}
for mod in (motions_a, motions_b, motions_c):
    allm.update(mod.M)

lib = open(os.path.join(os.path.dirname(__file__), '..', 'Momentum', 'Models', 'ExerciseLibrary.swift')).read()
ids = re.findall(r'ex\("(\w+)"', lib)
missing = [i for i in ids if i not in allm]
extra = [k for k in allm if k not in ids]
print(len(ids), 'exercises;', len(allm), 'motions; missing:', missing, 'extra:', extra)
if missing or extra:
    sys.exit(1)

def r(v, n): return round(float(v), n)

out = {}
for i in ids:
    m = allm[i]
    fr = m['frames']
    if m.get('loop', 'pingpong') == 'pingpong' and len(fr) > 2:
        frames = fr + fr[-2:0:-1]      # A B C -> A B C B (then loops back to A)
    else:
        frames = fr                    # 2 frames ping-pong naturally; 'cycle' loops as authored
    entry = {
        'view': m['view'], 'dur': m['dur'], 'held': m.get('held'), 'bounds': bbox(m),
        'props': [{'t': p['t'], 'p': [r(v, 3) for v in p['p']]} for p in m.get('props', [])],
        'frames': [[r(fr[0], 3), r(fr[1], 3)] + [r(v, 1) for v in fr[2:]] for fr in frames],
    }
    out[i] = entry

lines = ['// Generated by tools/export.py from tools/motions_*.py. Do not edit by hand.', '',
         '/// Keyframed skeleton poses for every exercise, as JSON. Decoded once by `MotionLibrary`.',
         'enum MotionData {', '    static let json = #"""', '{']
keys = list(out.keys())
for n, k in enumerate(keys):
    lines.append(json.dumps(k) + ':' + json.dumps(out[k], separators=(',', ':')) + (',' if n < len(keys) - 1 else ''))
lines += ['}', '"""#', '}', '']
dest = os.path.join(os.path.dirname(__file__), '..', 'Momentum', 'Design', 'MotionData.swift')
open(dest, 'w').write('\n'.join(lines))
print('wrote', dest, os.path.getsize(dest), 'bytes')
